### ISSUE TITLE
Traffic,Weather데이터 처리

### ISSUE THREAD

**Issue by qwerty1434** [hyunjuyo/team2_wanted_onboarding_2nd#57]
# 외부 데이터 활용에 대해 
#### 그래서 Traffic에서는 혼잡한 정도를 수치화했고, Weather에서는 기상악화를 T/F로 나타냈습니다
* ## Traffic_data
    1. 0시~23시까지의 값을 전부 더합니다
    2. 더했을 때 상위75%값인 42715를 넘으면 confusion = 1, 그렇지 않으면 0로 입력했습니다
    3. 다시한번 Date를 기준으로 groupby를 실시해 날짜를 기준으로 confusion을 더해 최종 복잡도를 계산했습니다
* ## Weather_data - 다음을 기준으로 Bad_Weather을 선정했습니다
    1. 일일 강수량이 80이상(폭우 기준)
    2. 일일 적설량이 5이상(데이터가 실제 대설주의보를 측정하는 신적설은 아닌것 같지만 적절한 기준이라 판단해 사용)
    3. 풍속이 4이상(임의로 설정한 기준)
     1~3조건 중 하나라도 만족하는 날은 Bad_Weather로 선정했습니다

해당 피처를 추가한 데이터로 RandomForestRegressor를 실시했을 때 성능향상이 있어 공유합니다

**Comment by hyunjuyo** [comment]
오 외부데이터 적용 시 좋은 참고가 될 것 같습니다~ 공유 감사합니다 :)

**Comment by sanghyun-Jung09** [comment]
이거 제가 노트북 램이 16gb인데도 pd.merge로 confusion구한거랑 원래 df가 안합쳐지는데 해결방법 아시는분 있으실까요?

**Comment by sooksok** [comment]
아이디어 감사합니다 : )
